### ISSUE TITLE
Question - Use Case

### ISSUE THREAD

**Issue by mingsai** [nbhr/php-reverse-proxy#1]
One purpose of the reverse proxy is to keep the origin proxy secret. I do not see how that is accomplished using this script which displays the origin in the get string. Putting the origin on the wire seems to defeat that use case. Am I missing something? 

Disclaimer - just read the readme first not the code.

Support for POST also seems like it would further the quest for a more secure option.

**Comment by benjemen** [comment]
It's in the read me. The line for the .httaccess does the job.

I just needed to updated the Lite Cache to the latest version 1.8.3., then it worked for me.
